// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttnpb

var GetGatewayConfigurationRequestFieldPathsNested = []string{
	"format",
	"gateway_ids",
	"gateway_ids.eui",
	"gateway_ids.gateway_id",
}

var GetGatewayConfigurationRequestFieldPathsTopLevel = []string{
	"format",
	"gateway_ids",
}
var GetGatewayConfigurationResponseFieldPathsNested = []string{
	"contents",
}

var GetGatewayConfigurationResponseFieldPathsTopLevel = []string{
	"contents",
}
