// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/gateway_configuration.proto

package ttnpb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetGatewayConfigurationRequest struct {
	GatewayIds           *GatewayIdentifiers `protobuf:"bytes,1,opt,name=gateway_ids,json=gatewayIds,proto3" json:"gateway_ids,omitempty"`
	Format               string              `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetGatewayConfigurationRequest) Reset()         { *m = GetGatewayConfigurationRequest{} }
func (m *GetGatewayConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayConfigurationRequest) ProtoMessage()    {}
func (*GetGatewayConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b59222464c10014, []int{0}
}
func (m *GetGatewayConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayConfigurationRequest.Unmarshal(m, b)
}
func (m *GetGatewayConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayConfigurationRequest.Merge(m, src)
}
func (m *GetGatewayConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayConfigurationRequest.Size(m)
}
func (m *GetGatewayConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayConfigurationRequest proto.InternalMessageInfo

func (m *GetGatewayConfigurationRequest) GetGatewayIds() *GatewayIdentifiers {
	if m != nil {
		return m.GatewayIds
	}
	return nil
}

func (m *GetGatewayConfigurationRequest) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type GetGatewayConfigurationResponse struct {
	Contents             []byte   `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayConfigurationResponse) Reset()         { *m = GetGatewayConfigurationResponse{} }
func (m *GetGatewayConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayConfigurationResponse) ProtoMessage()    {}
func (*GetGatewayConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b59222464c10014, []int{1}
}
func (m *GetGatewayConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayConfigurationResponse.Unmarshal(m, b)
}
func (m *GetGatewayConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayConfigurationResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayConfigurationResponse.Merge(m, src)
}
func (m *GetGatewayConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayConfigurationResponse.Size(m)
}
func (m *GetGatewayConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayConfigurationResponse proto.InternalMessageInfo

func (m *GetGatewayConfigurationResponse) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterType((*GetGatewayConfigurationRequest)(nil), "ttn.lorawan.v3.GetGatewayConfigurationRequest")
	proto.RegisterType((*GetGatewayConfigurationResponse)(nil), "ttn.lorawan.v3.GetGatewayConfigurationResponse")
}

func init() {
	proto.RegisterFile("lorawan-stack/api/gateway_configuration.proto", fileDescriptor_8b59222464c10014)
}

var fileDescriptor_8b59222464c10014 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8a, 0x13, 0x41,
	0x10, 0xc7, 0xe9, 0x80, 0xcb, 0xda, 0x2b, 0x22, 0x73, 0x31, 0x44, 0xd1, 0x35, 0x46, 0x8c, 0xe2,
	0x74, 0xeb, 0xe4, 0xa4, 0xb0, 0x04, 0x47, 0x64, 0xf1, 0xe0, 0x65, 0xbc, 0xb9, 0xec, 0x4a, 0x67,
	0x52, 0xe9, 0x34, 0xc9, 0x76, 0x8d, 0xdd, 0x95, 0x89, 0x31, 0xe6, 0xe2, 0xd1, 0xab, 0x8f, 0xe2,
	0x13, 0xf8, 0x0c, 0x3e, 0x81, 0xe0, 0x53, 0xec, 0x49, 0x98, 0x0f, 0x77, 0x43, 0x8c, 0x78, 0xeb,
	0xa2, 0xbe, 0x7e, 0xff, 0xea, 0x3f, 0x0f, 0xa7, 0xe8, 0xd4, 0x5c, 0xd9, 0xd0, 0x93, 0x4a, 0x27,
	0x52, 0x65, 0x46, 0x6a, 0x45, 0x30, 0x57, 0x8b, 0x77, 0x29, 0xda, 0x91, 0xd1, 0x33, 0xa7, 0xc8,
	0xa0, 0x15, 0x99, 0x43, 0xc2, 0xe0, 0x2a, 0x91, 0x15, 0x55, 0x8b, 0xc8, 0x7b, 0xad, 0xe7, 0xda,
	0xd0, 0x78, 0x36, 0x10, 0x29, 0x9e, 0x4a, 0xb0, 0x39, 0x2e, 0x32, 0x87, 0x1f, 0x16, 0xb2, 0x28,
	0x4e, 0x43, 0x0d, 0x36, 0xcc, 0xd5, 0xd4, 0x0c, 0x15, 0x81, 0xdc, 0x78, 0x94, 0x23, 0x5b, 0x37,
	0x35, 0xa2, 0x9e, 0x42, 0xb1, 0x5a, 0x59, 0x8b, 0x54, 0xec, 0xf3, 0x55, 0xf6, 0xee, 0x26, 0x9f,
	0x19, 0x82, 0x25, 0x33, 0x32, 0xe0, 0xaa, 0xa2, 0xf6, 0x37, 0xc6, 0x6f, 0x1d, 0x02, 0x1d, 0x96,
	0xe0, 0x2f, 0x2e, 0x72, 0x27, 0xf0, 0x7e, 0x06, 0x9e, 0x82, 0xd7, 0x7c, 0xaf, 0xd6, 0x65, 0x86,
	0xbe, 0xc9, 0xf6, 0x59, 0x77, 0x2f, 0x6a, 0x8b, 0x75, 0x39, 0xa2, 0x9a, 0xf0, 0xea, 0x7c, 0x43,
	0xbc, 0x7b, 0x16, 0x5f, 0xfa, 0xc2, 0x1a, 0xd7, 0x58, 0xc2, 0x75, 0x9d, 0xf5, 0x41, 0xcc, 0x77,
	0x46, 0xe8, 0x4e, 0x15, 0x35, 0x1b, 0xfb, 0xac, 0x7b, 0x39, 0x7e, 0x78, 0x16, 0xdf, 0x77, 0xf7,
	0x9a, 0x9d, 0xe8, 0xce, 0xc9, 0x91, 0x0a, 0x3f, 0x3e, 0x0e, 0x9f, 0x1e, 0x77, 0xfb, 0xcf, 0x8e,
	0xc2, 0xe3, 0x7e, 0x1d, 0x3e, 0x58, 0x46, 0x8f, 0x56, 0x9d, 0x4f, 0x27, 0x9d, 0xa4, 0xea, 0x6c,
	0x1f, 0xf0, 0xdb, 0x5b, 0xa1, 0x7d, 0x86, 0xd6, 0x43, 0xd0, 0xe2, 0xbb, 0x29, 0x5a, 0x02, 0x4b,
	0x25, 0xf2, 0x95, 0xe4, 0x4f, 0x1c, 0xfd, 0x64, 0xfc, 0xc6, 0xdf, 0x9a, 0xdf, 0x80, 0xcb, 0x4d,
	0x0a, 0xc1, 0x77, 0xc6, 0xaf, 0x6f, 0x99, 0x1f, 0x88, 0x0d, 0xe1, 0xff, 0xbc, 0x5e, 0x4b, 0xfe,
	0x77, 0x7d, 0x09, 0xde, 0x7e, 0xf9, 0xf9, 0xc7, 0xaf, 0xaf, 0x8d, 0x7e, 0x70, 0x20, 0x75, 0xea,
	0x6b, 0x47, 0x79, 0xb9, 0xbc, 0xf0, 0x07, 0xe2, 0xfc, 0xbd, 0x92, 0x6b, 0x5e, 0x93, 0xcb, 0xf2,
	0x42, 0xab, 0xf8, 0xc9, 0x5b, 0xa9, 0x51, 0xd0, 0x18, 0x68, 0x6c, 0xac, 0xf6, 0xc2, 0x02, 0xcd,
	0xd1, 0x4d, 0xe4, 0xba, 0x29, 0xf2, 0x9e, 0xcc, 0x26, 0x5a, 0x12, 0xd9, 0x6c, 0x30, 0xd8, 0x29,
	0x2c, 0xd1, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x75, 0xd9, 0x33, 0xd9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayConfigurationServiceClient is the client API for GatewayConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayConfigurationServiceClient interface {
	GetGatewayConfiguration(ctx context.Context, in *GetGatewayConfigurationRequest, opts ...grpc.CallOption) (*GetGatewayConfigurationResponse, error)
}

type gatewayConfigurationServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayConfigurationServiceClient(cc *grpc.ClientConn) GatewayConfigurationServiceClient {
	return &gatewayConfigurationServiceClient{cc}
}

func (c *gatewayConfigurationServiceClient) GetGatewayConfiguration(ctx context.Context, in *GetGatewayConfigurationRequest, opts ...grpc.CallOption) (*GetGatewayConfigurationResponse, error) {
	out := new(GetGatewayConfigurationResponse)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.GatewayConfigurationService/GetGatewayConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayConfigurationServiceServer is the server API for GatewayConfigurationService service.
type GatewayConfigurationServiceServer interface {
	GetGatewayConfiguration(context.Context, *GetGatewayConfigurationRequest) (*GetGatewayConfigurationResponse, error)
}

// UnimplementedGatewayConfigurationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayConfigurationServiceServer struct {
}

func (*UnimplementedGatewayConfigurationServiceServer) GetGatewayConfiguration(ctx context.Context, req *GetGatewayConfigurationRequest) (*GetGatewayConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayConfiguration not implemented")
}

func RegisterGatewayConfigurationServiceServer(s *grpc.Server, srv GatewayConfigurationServiceServer) {
	s.RegisterService(&_GatewayConfigurationService_serviceDesc, srv)
}

func _GatewayConfigurationService_GetGatewayConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayConfigurationServiceServer).GetGatewayConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.GatewayConfigurationService/GetGatewayConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayConfigurationServiceServer).GetGatewayConfiguration(ctx, req.(*GetGatewayConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayConfigurationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.GatewayConfigurationService",
	HandlerType: (*GatewayConfigurationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayConfiguration",
			Handler:    _GatewayConfigurationService_GetGatewayConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/gateway_configuration.proto",
}
